package com.foreverinlove.objects

data class DiscoverFilterObject(
    var distanceUnit: String? = "",
    var min_age: String? = "",
    var max_age: String? = "",
    var latitude: String? = "",
    var longitude: String? = "",
    var page: String? = "",
    var pageSize: String? = "",
    var education: String? = "",
    var minDistance: String? = "",
    var maxDistance: String? = "",
    var arts: String? = "",
    var covidVaccine: String? = "",
    var dietaryLifestyle: String? = "",
    var drink: String? = "",
    var drugs: String? = "",
    var firstDateIceBreaker: String? = "",
    var horoscope: String? = "",
    var interests: String? = "",
    var language: String? = "",
    //var userLookingFor: String? = "",
    var listedLookingFor: String? = "",
    var pets: String? = "",
    var politicalLeaning: String? = "",
    var relationshipStatus: String? = "",
    var religion: String? = "",
    var smoking: String? = "",
    var isApplyFilter: String? = "",
    var minHeight: String? = "",
    var maxHeight: String? = "",
    var hobbies: String? = "",
    var address: String? = "",

):java.io.Serializable